services:
  _defaults:
    autowire: true
    autoconfigure: true

  Aggrego\Component\Symfony\TerminalUserComponent\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'