# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    messenger:
        default_bus: default
        buses:
            default: ~
        transports:
            sync: 'sync://'

        routing:
            Aggrego\Component\BoardComponent\Contract\Application\UseCases\CreateBoard\CreateBoardCommand: sync

    cache:
        directory: 'var/pools'
        pools:
            local_database:
                default_lifetime: 3600
                adapter: cache.adapter.filesystem

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
